version: 2

models:
  - name: fact_order_items
    columns:
      - name: order_id
        tests:
          - not_null
      - name: product_id
        tests:
          - not_null
      - name: category
        tests:
          - not_null

  - name: order_metrics
    columns:
      - name: category
        tests:
          - not_null

  - name: trust_signal_rollups
    columns:
      - name: metric_date
        tests:
          - not_null
          - unique
      - name: on_time_delivery_rate
        tests:
          - not_null
      - name: csr_badge_coverage
        tests:
          - not_null
