version: 2

models:
  - name: fact_order_items
    columns:
      - name: order_id
        tests:
          - not_null
      - name: product_id
        tests:
          - not_null
      - name: category
        tests:
          - not_null

  - name: order_metrics
    columns:
      - name: category
        tests:
          - not_null
  - name: fact_stock_alerts
    columns:
      - name: area_id
        tests:
          - not_null
      - name: severity
        tests:
          - not_null
