data_pipeline:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost # Changed postgres_dw to localhost
      user: dwh_user
      password: dwh_password
      port: 5432
      dbname: datamart
      schema: public