data_pipeline:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres_dw
      user: dwh_user
      password: "{{ env_var('POSTGRES_DWH_PASSWORD') }}"
      port: 5432
      dbname: datamart
      schema: analytics
      threads: 4
