version: 2

models:
  - name: stg_order_items
    columns:
      - name: order_id
        tests:
          - not_null
      - name: customer_id
        tests:
          - not_null
      - name: product_id
        tests:
          - not_null

  - name: stg_products
    columns:
      - name: product_id
        tests:
          - not_null
          - unique

  - name: stg_payments
    columns:
      - name: payment_id
        tests:
          - not_null
          - unique

  - name: stg_customers
    columns:
      - name: customer_id
        tests:
          - not_null
          - unique

  - name: stg_support_cases
    columns:
      - name: case_id
        tests:
          - not_null
          - unique
      - name: customer_id
        tests:
          - not_null

  - name: stg_logistics_delivery_status
    columns:
      - name: shipment_id
        tests:
          - not_null
          - unique
      - name: order_id
        tests:
          - not_null

  - name: stg_logistics_stockist_inventory
    columns:
      - name: stockist_id
        tests:
          - not_null
          - unique

  - name: stg_logistics_distributor_master
    columns:
      - name: distributor_id
        tests:
          - not_null
          - unique
