version: 2

sources:
  - name: raw
    schema: raw
    tables:
      - name: raw_data
      - name: products
      - name: payments
      - name: customers_source
      - name: support_cases
      - name: logistics_delivery_status
      - name: logistics_stockist_inventory
      - name: logistics_distributor_master
