version: 2

sources:
  - name: raw
    schema: raw
    tables:
      - name: raw_data
      - name: products
      - name: payments
      - name: customers_source
      - name: deliveries
      - name: support_interactions
      - name: csr_badges
