version: 2

sources:
  - name: raw
    schema: raw
    tables:
      - name: raw_data
      - name: products
      - name: payments
      - name: customers_source
  - name: analytics
    schema: analytics
    tables:
      - name: fact_stock_alerts
