version: 2

sources:
  - name: raw
    schema: raw
    tables:
      - name: raw_data
      - name: products
      - name: payments
      - name: customers_source
      - name: delivery_status_feed
      - name: distributor_master
      - name: stockist_inventory_snapshot
      - name: deliveries
      - name: support_interactions
      - name: csr_badges
