CREATE SCHEMA IF NOT EXISTS analytics;

CREATE TABLE IF NOT EXISTS analytics.mart_trust_scores (
    metric_date DATE PRIMARY KEY,
    orders_count INTEGER,
    deliveries_count INTEGER,
    on_time_delivery_rate NUMERIC(5,2),
    on_time_rate_rolling_7d NUMERIC(5,2),
    on_time_rate_rolling_30d NUMERIC(5,2),
    on_time_below_threshold BOOLEAN,
    csr_badge_coverage NUMERIC(5,2),
    csr_badge_coverage_rolling_30d NUMERIC(5,2),
    csr_badge_below_threshold BOOLEAN,
    avg_resolution_minutes NUMERIC(6,2),
    avg_resolution_minutes_rolling_30d NUMERIC(6,2),
    resolution_above_threshold BOOLEAN,
    resolution_success_rate NUMERIC(5,2),
    resolution_success_rate_rolling_30d NUMERIC(5,2),
    overall_trust_score NUMERIC(5,2),
    trust_score_rolling_30d NUMERIC(5,2),
    trust_health_status TEXT,
    breach_flag BOOLEAN,
    delivery_data_available BOOLEAN,
    csr_data_available BOOLEAN,
    support_data_available BOOLEAN,
    last_refreshed_at TIMESTAMPTZ DEFAULT NOW()
);

INSERT INTO analytics.mart_trust_scores (
    metric_date,
    orders_count,
    deliveries_count,
    on_time_delivery_rate,
    on_time_rate_rolling_7d,
    on_time_rate_rolling_30d,
    on_time_below_threshold,
    csr_badge_coverage,
    csr_badge_coverage_rolling_30d,
    csr_badge_below_threshold,
    avg_resolution_minutes,
    avg_resolution_minutes_rolling_30d,
    resolution_above_threshold,
    resolution_success_rate,
    resolution_success_rate_rolling_30d,
    overall_trust_score,
    trust_score_rolling_30d,
    trust_health_status,
    breach_flag,
    delivery_data_available,
    csr_data_available,
    support_data_available,
    last_refreshed_at
) VALUES
    (
        CURRENT_DATE - INTERVAL '2 days',
        425,
        410,
        92.5,
        93.1,
        94.2,
        FALSE,
        88.2,
        87.9,
        FALSE,
        45.3,
        46.7,
        FALSE,
        96.4,
        95.8,
        91.2,
        90.7,
        'healthy',
        FALSE,
        TRUE,
        TRUE,
        TRUE,
        NOW()
    ),
    (
        CURRENT_DATE - INTERVAL '1 day',
        468,
        452,
        93.7,
        93.9,
        94.5,
        FALSE,
        89.1,
        88.4,
        FALSE,
        43.6,
        45.1,
        FALSE,
        96.9,
        96.1,
        92.5,
        91.3,
        'healthy',
        FALSE,
        TRUE,
        TRUE,
        TRUE,
        NOW()
    ),
    (
        CURRENT_DATE,
        512,
        497,
        94.8,
        94.1,
        94.9,
        FALSE,
        90.3,
        89.2,
        FALSE,
        41.8,
        43.9,
        FALSE,
        97.5,
        96.6,
        93.4,
        92.1,
        'healthy',
        FALSE,
        TRUE,
        TRUE,
        TRUE,
        NOW()
    )
ON CONFLICT (metric_date) DO UPDATE SET
    orders_count = EXCLUDED.orders_count,
    deliveries_count = EXCLUDED.deliveries_count,
    on_time_delivery_rate = EXCLUDED.on_time_delivery_rate,
    on_time_rate_rolling_7d = EXCLUDED.on_time_rate_rolling_7d,
    on_time_rate_rolling_30d = EXCLUDED.on_time_rate_rolling_30d,
    on_time_below_threshold = EXCLUDED.on_time_below_threshold,
    csr_badge_coverage = EXCLUDED.csr_badge_coverage,
    csr_badge_coverage_rolling_30d = EXCLUDED.csr_badge_coverage_rolling_30d,
    csr_badge_below_threshold = EXCLUDED.csr_badge_below_threshold,
    avg_resolution_minutes = EXCLUDED.avg_resolution_minutes,
    avg_resolution_minutes_rolling_30d = EXCLUDED.avg_resolution_minutes_rolling_30d,
    resolution_above_threshold = EXCLUDED.resolution_above_threshold,
    resolution_success_rate = EXCLUDED.resolution_success_rate,
    resolution_success_rate_rolling_30d = EXCLUDED.resolution_success_rate_rolling_30d,
    overall_trust_score = EXCLUDED.overall_trust_score,
    trust_score_rolling_30d = EXCLUDED.trust_score_rolling_30d,
    trust_health_status = EXCLUDED.trust_health_status,
    breach_flag = EXCLUDED.breach_flag,
    delivery_data_available = EXCLUDED.delivery_data_available,
    csr_data_available = EXCLUDED.csr_data_available,
    support_data_available = EXCLUDED.support_data_available,
    last_refreshed_at = NOW();
