version: 2

models:
  - name: customers
    description: "Table containing customer information for the ecommerce online retail store."
    columns:
      - name: customer_id
        description: "Primary key: Unique identifier for each customer."
        data_type: "integer"
      - name: first_name
        description: "Customer's first name."
        data_type: "varchar"
      - name: last_name
        description: "Customer's last name."
        data_type: "varchar"
      - name: email
        description: "Customer's email address; should be unique."
        data_type: "varchar"
      - name: phone
        description: "Customer's primary contact number."
        data_type: "varchar"
      - name: address
        description: "Complete shipping address for the customer."
        data_type: "text"
      - name: created_at
        description: "Timestamp when the customer account was created."
        data_type: "timestamp"

  - name: orders
    description: "Table storing customer orders for the online store."
    columns:
      - name: order_id
        description: "Primary key: Unique identifier for each order."
        data_type: "integer"
      - name: customer_id
        description: "Foreign key linking to the customers table."
        data_type: "integer"
      - name: order_date
        description: "Date and time when the order was placed."
        data_type: "timestamp"
      - name: status
        description: "Order status, e.g., Pending, Shipped, Delivered, or Cancelled."
        data_type: "varchar"
      - name: total_amount
        description: "Total monetary value of the order."
        data_type: "numeric"
      - name: payment_method
        description: "Method of payment used (e.g., Credit Card, PayPal)."
        data_type: "varchar"
      - name: shipping_address
        description: "Delivery address for the order, which may differ from the customer's default address."
        data_type: "text"

  - name: products
    description: "Table listing all products available in the online retail store."
    columns:
      - name: product_id
        description: "Primary key: Unique identifier for each product."
        data_type: "integer"
      - name: name
        description: "Name of the product."
        data_type: "varchar"
      - name: description
        description: "Detailed description of the product."
        data_type: "text"
      - name: price
        description: "Retail price of the product."
        data_type: "numeric"
      - name: category
        description: "Category or classification that the product belongs to."
        data_type: "varchar"
      - name: stock_quantity
        description: "Available inventory count for the product."
        data_type: "integer"
      - name: created_at
        description: "Timestamp when the product was added to the catalog."
        data_type: "timestamp"

  - name: reviews
    description: "Table capturing customer reviews on products."
    columns:
      - name: review_id
        description: "Primary key: Unique identifier for each review."
        data_type: "integer"
      - name: product_id
        description: "Foreign key linking to the products table."
        data_type: "integer"
      - name: customer_id
        description: "Foreign key linking to the customers table."
        data_type: "integer"
      - name: rating
        description: "Numerical rating provided by the customer, typically from 1 (poor) to 5 (excellent)."
        data_type: "integer"
      - name: review_text
        description: "Optional textual review provided by the customer."
        data_type: "text"
      - name: review_date
        description: "Timestamp when the review was submitted."
        data_type: "timestamp"
