version: 2
sources:
  - name: raw
    description: "Raw data source for the eCommerce platform before processing and transformations."
    schema: raw  # Adjust if your raw tables use a different schema
    tables:
      - name: raw_data
        description: "Raw order transactions from the eCommerce store."
        columns:
          - name: order_id
            description: "Unique identifier for each order. (May be repeated if an order has multiple products.)"
            tests:
              - not_null
          - name: customer_id
            description: "Unique identifier for the customer."
            tests:
              - not_null
          - name: order_date
            description: "Timestamp when the order was placed."
            tests:
              - not_null
          - name: total_amount
            description: "Total order monetary value."
            tests:
              - not_null
          - name: order_level_payment_status
            description: "Payment status at the order level (e.g. Paid, Pending, Refunded)."
            tests:
              - accepted_values:
                  values: ["Paid", "Pending", "Refunded"]
          - name: product_id
            description: "Unique product identifier."
            tests:
              - not_null

      - name: products
        description: "Product catalog with product details."
        columns:
          - name: product_id
            description: "Unique identifier for each product."
            tests:
              - not_null
              - unique
          - name: product_name
            description: "Name of the product."
            tests:
              - not_null
          - name: category
            description: "Category for the product (e.g., Electronics, Apparel)."
            tests:
              - not_null
          - name: price
            description: "Price of the product."
            tests:
              - not_null

      - name: payments
        description: "Raw payment transactions processed for orders."
        columns:
          - name: payment_id
            description: "Unique identifier for each payment transaction."
            tests:
              - not_null
              - unique
          - name: order_id
            description: "Order ID linked to the payment."
            tests:
              - not_null
          - name: payment_method
            description: "Payment method used (e.g., Credit Card, PayPal, Bank Transfer)."
            tests:
              - accepted_values:
                  values: ["Credit Card", "PayPal", "Bank Transfer"]
          - name: transaction_payment_status
            description: "Status of the payment transaction (e.g., Completed, Failed, Pending)."
            tests:
              - accepted_values:
                  values: ["Completed", "Failed", "Pending", "Refunded"]

      - name: customers_source
        description: "Customer demographic and contact information."
        columns:
          - name: customer_id
            description: "Unique identifier for each customer."
            tests:
              - not_null
              - unique
          - name: email
            description: "Customer's email address."
            tests:
              - unique
          - name: signup_date
            description: "Timestamp when the customer signed up."
            tests:
              - not_null
